# Generated by Django 5.0.7 on 2024-08-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drones',
            new_name='Drone',
        ),
        migrations.RenameField(
            model_name='pilot',
            old_name='race_count',
            new_name='races_count',
        ),
    ]
