# Generated by Django 5.0.7 on 2024-08-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_rename_drones_drone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='has_it_completed',
            new_name='has_it_competed',
        ),
    ]
