# Generated by Django 5.0.7 on 2024-08-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_rename_has_it_completed_drone_has_it_competed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilot', to='drones.pilot'),
        ),
    ]
